config/routes.rb
SabisuRails::Engine.routes.draw do
  get "explorer", to: "explorer#index"
end

app/controllers/sabisu_rails/application_controller.rb
module SabisuRails
  class ApplicationController < ActionController::Base
    
  end
end

app/controllers/sabisu_rails/base_controller.rb
module SabisuRails
  class BaseController < ApplicationController

    layout SabisuRails.layout

    before_filter :authenticate

    protected

      def authenticate
        authenticate_or_request_with_http_basic do |username, password|
          username == SabisuRails.authentication_username && password == SabisuRails.authentication_password
        end
      end
  end
end

app/controllers/sabisu_rails/explorer_controller.rb
module SabisuRails
  class ExplorerController < SabisuRails::BaseController

    def index
      @resources = SabisuRails.resources_names
      @explorer = SabisuRails::Explorer.new(params[:explorer] || {})
      @response = SabisuRails::Request.new(@explorer, params[@explorer.resource_name], params[:explorer]).response
      respond_to do |format|
        format.html
        format.js
      end
    end

  end
end

app/helpers/sabisu_rails/explorer_helper.rb
module SabisuRails::ExplorerHelper

  def label_attribute(explorer, attr)
    explorer.required_attribute?(attr) ? "* #{attr.capitalize}" : attr.capitalize
  end

  def active_resource_state(resource)
    loaded_resource = SabisuRails.default_resource.to_s
    if params[:explorer].nil?
      "active" if loaded_resource  == resource
    else
      "active" if params[:explorer][:resource] == resource
    end
  end

  def prettify_headers(headers)
    html = ""
    headers.each do |k, v|
      k = k.titleize.split(' ').join('-')
      header_name = content_tag :span, k, class: 'text-muted text-strong'
      arrow = content_tag :span," <i class='fa fa-long-arrow-right'></i> ".html_safe, class: 'text-muted'
      header_value = content_tag :span, v, class: 'text-muted'
      html << (header_name + arrow + header_value)
      html << "<br />"
    end
    html.html_safe
  end
end

app/helpers/sabisu_rails_helper.rb
module SabisuRailsHelper

end

app/views/layouts/sabisu.html.erb
<html lang="en">

<head>
  <!--includes meta tags, title and more header definitions-->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no">
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">

  <title>Sabisu Explorer</title>

  <!-- Furatto core CSS -->
  <%= stylesheet_link_tag "sabisu_rails/application", :cache => true %>
  <%= csrf_meta_tag %>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>
  <%= yield %>
  <%= javascript_include_tag "sabisu_rails/application" %>
  <%= yield :javascripts %>
</body>
</html>

app/views/sabisu_rails/explorer/index.html.erb
<div class="row">
  <div class="col-2 nopadding">
    <ul class="navigation side">
      <li class="header"><%= SabisuRails.app_name %> - <br /> Api Explorer</li>
      <% @resources.each do |resource| %>
        <li class="<%= active_resource_state(resource) %>"><%= link_to resource.classify, explorer_path(explorer: { resource: resource }) %></li>
    <% end %>
    </ul>
  </div>
  <div class="col-10 nopadding">
    <div class="main-content">
      <div class="row">
          <%= simple_form_for :explorer, url: explorer_path, html: {id: 'explorer_form'}, method: :get, remote: true do |f| %>
            <%= f.hidden_field :resource, value: @explorer.resource %>
          <div class="row">
            <div class="col-6">
              <div class="input-addon">
                <a class="addon"><%= "/#{@explorer.resource}/" %></a>
                <%= f.text_field :uri_pattern, value: @explorer.uri_pattern, placeholder: "URI pattern. 1 or bids or orders/1", class: "addon-field" %>
              </div>
            </div>
            <div class="col-2">
              <%= f.select :http_method, options_for_select(SabisuRails.http_methods, @explorer.http_method.upcase) %>
            </div>
            <div class="col-2">
              <a href="#" class="button radius block nomargin three-d explorer-fields-link-js" data-target="#url_params_inputs" data-type="url_params"><i class="fa fa-link"></i>Url params</a>
            </div>
            <div class="col-2">
              <a href="#" class="button radius block nomargin three-d explorer-fields-link-js" data-target="#header_inputs" data-type="headers"><i class="fa fa-indent"></i> Headers</a>
            </div>
          </div>
          <br />

          <div class="appeareable">
            <% @explorer.resource_columns.each do |column| %>
              <%= f.input column, input_html: {name: "#{@explorer.resource_name}[#{column}]" }, as: @explorer.column_type(column), required: @explorer.required_attribute?(column) %>
          <% end %>
          </div>

          <div class="row">
             <div class="col-5">
              <fieldset>
                <legend>Url params (<span class="label round" id="url_params_counter_js">0</span>)</legend>
                <div class="row" id="url_params_inputs">

                </div>
              </fieldset>
             </div>
             <div class="col-1">
               
             </div>
             <div class="col-5">
              <fieldset>
                <legend>Headers (<span class="label round" id="headers_counter_js">0</span>)</legend>
                <div class="row" id="header_inputs">

                </div>
              </fieldset>
             </div>
          </div>
          <%= f.submit "Send", class: 'button radius three-d success', data: { :disable_with => "Processing..." } %>
        <% end %>
      </div>

      <div class="response-wrapper">

      <div class="row">
        <div class="response-details">
           <ul class="navigation inline">
             <li><small><strong>STATUS:</strong></small> <span class="label primary radius" id="response_status"><%= @response.code %></span></li>
             <li><small><strong>TIME:</strong></small> <span class="label primary radius" id="response_time"><%= @response.headers['x-runtime'] %> ms</span></li>
           </ul>
        </div>
        <ul class="navigation inline" data-tabu>
          <li><a href="#result">Body</a></li>
          <li><a href="#headers_result">(<span id="headers_count"><%= @response.headers.count %></span>) Headers</a></li>
        </ul>
        <div class="tabu-content">
          <div class="content row" id="result">
          </div>
          <div class="content row headers" id="headers_result">
            <%= prettify_headers @response.headers %>
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>

<%= content_for :javascripts do %>
  <script type="text/javascript" charset="utf-8">
$(document).ready(function(){
    $.JSONView(<%= @response.body.html_safe %>, $('#result'));
    });
</script>
<% end %>

app/views/sabisu_rails/explorer/index.js.erb
$.JSONView(<%= @response.body.html_safe %>, $('#result'));
$("#response_status").text(<%= @response.code %>);
$("#response_time").text(<%= @response.headers['x-runtime'] %>);
$('#headers_result').html("<%= j prettify_headers @response.headers %>");
$('#headers_count').text(<%= @response.headers.count %>)
Pace.stop();